#======= Prison 2.0 Configuration =======#
#           (C) 2016 SirFaizdat          #
#========================================#

server-prefix: "&4Prison &7>"
check-updates: true
opt-out: false

# Multiworld prohibits players from using prison commands in worlds not listed below.
# It is useful for servers that want to designate certain worlds towards prison.
# To use this feature, set multiworld to true and add the desired worlds in world-list.
multiworld: false
world-list: [plots, mines]

# The enable block tells Prison whether or not to enable a component.
# Changes in this block will not take effect until the SERVER is reloaded or restarted.
enable:
  mines: true
  ranks: true
  autosmelt: true
  autoblock: true

# Mines Settings

reset-time: 10
reset-warnings: [10,5,1]
reset-warning-message: "&7Mines are going to reset in &3<mins> minutes&7."
reset-broadcast-message: "&3All mines have been reset."
fill-mode: true
async-reset: true

# Ranks Settings

fireworks-on-rankup: true

# Autosmelt Setings

flames-on-autosmelt: true